### ISSUE TITLE
Type stubs for versions 0.20.18 and up

### ISSUE THREAD

**Issue by nmclellan** [StefanBRas/polugins#72]
Thanks for working on this! Would it be possible to cut a new release with the stubs for the recent versions of Polars (0.20.18 -> 0.20.22)? Hoping its not too much trouble based on https://github.com/StefanBRas/polugins/issues/57.  

Thanks!

**Comment by StefanBRas** [comment]
Yeah sure, I'll cut a release later today.

**Comment by StefanBRas** [comment]
Done!
