### ISSUE TITLE
Generate stub for new version of polars

### ISSUE THREAD

**Issue by gab23r** [StefanBRas/polugins#81]
The last version available is 0.20.28 which is super old. I am aware of this #80, I don't realise the amount of effort it require.
Do you think that in the meantime you can push stubs for a newer veriosn of polars ?

Thanks a lot !

NB: My workaround today is to copy paste the entire polars/dateframe/frame.py file into typings/polars/dataframe/frame.pyi (without removing body's function ! ) and I had my namespace manually. It do the job but some manual work...

**Comment by StefanBRas** [comment]
I have #80 mostly done - the difficult thing has been to test it, because I haven't been able to find some nice way to test stubs. But the current stubs has errors anyway, so these just need to have less

I'll try to release it soon - maybe tomorrow

**Comment by StefanBRas** [comment]
I have published a pre-release now - Could you try it out and verify that it works? I looked over it and it looks correct, but i'd like to have someone try it on an actual project before actually releasing it
The version is `0.6.0rc0`

**Comment by gab23r** [comment]
Will do asap

**Comment by StefanBRas** [comment]
You have to install into the same venv as the version of Polaris that you're using by the way. I'll probably add other ways later

**Comment by gab23r** [comment]
It works for me 🥳👌
