### ISSUE TITLE
Load namespace in submodule

### ISSUE THREAD

**Issue by gab23r** [StefanBRas/polugins#84]
It think that that only the namespaces that are imported at the top level are correctly managed by polugins.
For example my namespace is imported like this:
`from my_package.sub_module import MyNameSpace`

But in typings/ there is at the top `import my_package` and not `import my_package.sub_module` so my namespace is not loaded

**Comment by StefanBRas** [comment]
Hmm, that seems wrong yes. I probably only tested with top level modules.

Thanks for reporting! I'll implement it and probably push a 0.6.0rc1 version and ask you to test it

**Comment by StefanBRas** [comment]
@gab23r I pushed a fix now, can you try it? It's versioned as "0.6.0rc1"

**Comment by gab23r** [comment]
Will tomorrow

**Comment by StefanBRas** [comment]
Great, I'll release sometime over the weekend then
